version: '3'

services:
  manage-repositories:
    image: ghcr.io/micaeladominguez/snippet-manage-repositories:0.0.1
    ports:
      - "8081:8080"

  testing-scripts:
    image: ghcr.io/micaeladominguez/snippet-testing-scripts:0.0.1
    ports:
      - "8082:8080"

  management-service:
    image: ghcr.io/micaeladominguez/snippet-managment-service-snippet:0.0.1
    ports:
      - "8083:8080"

  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_LOGS_ENABLED=${DD_LOGS_ENABLED}
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=${DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL}
      - DD_CONTAINER_EXCLUDE_LOGS=${DD_CONTAINER_EXCLUDE_LOGS}
      - DD_SITE=${DD_SITE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - datadog-agent-run:/opt/datadog-agent/run:rw

volumes:
  datadog-agent-run:
